version: 0.0
os: linux
files:
  - source: /
    destination: /usr/cddemo
    overwrite: true
permission:
  - object: /usr/cddemo/codedeploy
    pattern: "*.sh"
    owner: root
    group: root
    mode: 775
    type:
    - file
hooks:
  BeforeInstall:
    - location: codedeploy/before_install.sh
      runas: root
      timeout: 180
  AfterInstall:
    - location: codedeploy/after_install.sh
      runas: root
      timeout: 180
  ApplicationStart:
    - location: codedeploy/app_start.sh
      runas: root
      timeout: 180
  ApplicationStop:
    - location: codedeploy/app_stop.sh
      runas: root
      timeout: 180
  ValidateService:
    - location: codedeploy/validate_service.sh
      timeout: 180